/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_irwin_animwebp_AnimWebPMaker */

#ifndef _Included_com_irwin_animwebp_AnimWebPMaker
#define _Included_com_irwin_animwebp_AnimWebPMaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_irwin_animwebp_AnimWebPMaker
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_irwin_animwebp_AnimWebPMaker_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_irwin_animwebp_AnimWebPMaker
 * Method:    nativeMakeOnce
 * Signature: ([Ljava/lang/String;ZIIFLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_irwin_animwebp_AnimWebPMaker_nativeMakeOnce
  (JNIEnv *, jclass, jobjectArray, jboolean, jint, jint, jfloat, jstring);

/*
 * Class:     com_irwin_animwebp_AnimWebPMaker
 * Method:    nativeSetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_irwin_animwebp_AnimWebPMaker_nativeSetup
  (JNIEnv *, jobject);

/*
 * Class:     com_irwin_animwebp_AnimWebPMaker
 * Method:    config
 * Signature: (IIZZI)V
 */
JNIEXPORT void JNICALL Java_com_irwin_animwebp_AnimWebPMaker_config
  (JNIEnv *, jobject, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     com_irwin_animwebp_AnimWebPMaker
 * Method:    nativeAddImage
 * Signature: ([BIIFZ)I
 */
JNIEXPORT jint JNICALL Java_com_irwin_animwebp_AnimWebPMaker_nativeAddImage
  (JNIEnv *, jobject, jbyteArray, jint, jint, jfloat, jboolean);

/*
 * Class:     com_irwin_animwebp_AnimWebPMaker
 * Method:    make
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_irwin_animwebp_AnimWebPMaker_make
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_irwin_animwebp_AnimWebPMaker
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_irwin_animwebp_AnimWebPMaker_nativeRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_irwin_animwebp_AnimWebPMaker
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_irwin_animwebp_AnimWebPMaker_nativeFinalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
