/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_irwin_webplib_WebpProcessor */

#ifndef _Included_com_irwin_webplib_WebpProcessor
#define _Included_com_irwin_webplib_WebpProcessor
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_irwin_webplib_WebpProcessor_compose
  (JNIEnv *, jobject, jobjectArray, jboolean,jint, jint, jfloat, jstring);

#ifdef __cplusplus
}
#endif
#endif
